version: "3.8"
services:
  python-api:
    build: .
    ports:
      - target: 80
        published: 80
    depends_on:
      - redis
    networks:
      - default
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - default